export const Users = [
    {
      id:1,
      profilePicture: "https://i.insider.com/5cb8b133b8342c1b45130629?width=700",
      username: "Sejal Zambare",
    },
    {
      id:2,
      profilePicture: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/09/27/08/jennifer-lawrence.jpg?width=982&height=726&auto=webp&quality=75",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "https://live-production.wcms.abc-cdn.net.au/a35f959ac610c16932e3fcfa4c691326?impolicy=wcms_crop_resize&cropH=2079&cropW=3696&xPos=0&yPos=188&width=862&height=485",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/dwayne-johnson-attends-the-premiere-of-universal-pictures-news-photo-1161880409-1566504158.jpg?crop=0.762xw:0.654xh;0.0698xw,0.0141xh&resize=480:*",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "https://bsmedia.business-standard.com/_media/bs/img/article/2021-10/19/full/1634583924-2716.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "https://www.scienceofpeople.com/wp-content/uploads/2020/06/1072688_PeoplePleaser_1250px_051921.png",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcJAfEXywyM6bSaRs-p7d4PFeBXMb9bYHo1A&usqp=CAU",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBNreWX0jRYZvE-PLfyB5xMSKXyyW64Fx5ljqBIXYexpOcEynvmahmffp9KTSqMjV9nfM&usqp=CAU",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "https://images.everydayhealth.com/images/tips-for-people-newly-diagnosed-with-multiple-sclerosis-alt-1440x810.jpg",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "https://images.ctfassets.net/u4vv676b8z52/60zM6XTHxGoqD9Am2KllNr/9c671ede560f911271385a0e19a1299e/why-people-wink-hero-678x4446-compressor.jpg?fm=jpg&q=80",
      username: "Ross Geller",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://www.happybrainscience.com/wp-content/uploads/2017/07/derwent-morning-Cropped.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://i.ytimg.com/vi/BHACKCNDMW8/maxresdefault.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://i.pinimg.com/originals/fc/f6/a2/fcf6a2435357d6770c675e37c623ad39.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://wallpaperaccess.com/full/1163657.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxNgUXgvfBz3Hh3VAlONbuECdQQToO0T83ZA&usqp=CAU",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://images.theconversation.com/files/405990/original/file-20210611-13-pcdwbd.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "https://4kwallpapers.com/images/walls/thumbs_2t/6743.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYXXjRLTKQi1YNTLYedKTViI-1YbuHyn6oMQ&usqp=CAU",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStY5uLXit-Iyy5n4FzVDLGbV45BIkdgSLCHQ&usqp=CAU",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://wallpapercave.com/wp/yIcMVnO.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];